### PR TITLE
Alternative implementation for JSONCodec.PlanScan

### LINKED ISSUE #2229: Potential regression in `sql.Scanner` handling when using `pgx.CollectRows`
**Describe the bug**

As of `v5.7.2` When using `pgx.CollectRows` to collect rows into a struct that contains a pointer to a struct that implements `sql.Scanner`, if the column in the database is `NULL`, the corresponding struct is no longer `nil`.

* `v5.7.1` - the example below prints `testData[1].Value was nil struct` and the `testData[1].Value` is `nil` as expected.
* `v5.7.2` - the example below prints `expected testData[1].Value to be nil struct` and the `testData[1].Value` is no longer nil.

This seems to have been introduced with https://github.com/jackc/pgx/pull/2151, is this an expected change? 
Is it possible to work around this to ensure that the pointer values are still nil?

**To Reproduce**

If possible, please provide runnable example such as:

```
package main

import (
	"context"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"

	embeddedpostgres "github.com/fergusstrange/embedded-postgres"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type TestData struct {
	Id    string     `db:"id"`
	Value *TestValue `db:"value"`
}

func (e *TestData) RewriteQuery(ctx context.Context, conn *pgx.Conn, sql string, args []any) (newSQL string, newArgs []any, err error) {
	return `
		INSERT INTO
			pgx_test (
				id,
				value
			)
		VALUES
			($1, $2)
	`, []any{e.Id, e.Value}, nil
}

type TestValue struct {
	Data string `json:"data"`
}

func (t *TestValue) Scan(src interface{}) error {
	if src == nil {
		return nil
	}

	var source []byte
	switch val := src.(type) {
	case string:
		source = []byte(val)
	case []byte:
		source = val
	default:
		return errors.New("incompatible source type")
	}

	if err := json.Unmarshal(source, &t); err != nil {
		return fmt.Errorf("unable to unmarshal source data: %w", err)
	}

	return nil
}

func (t *TestValue) Value() (driver.Value, error) {
	if t == nil {
		return nil, nil
	}

	testValueBytes, err := json.Marshal(t)
	if err != nil {
		return nil, fmt.Errorf("unable to marshal test value data: %w", err)
	}

	return testValueBytes, nil
}

func main() {
	ctx := context.TODO()

	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	slog.SetDefault(logger)

	postgres := embeddedpostgres.NewDatabase(embeddedpostgres.DefaultConfig().Port(5555).Logger(nil))
	if err := postgres.Start(); err != nil {
		slog.Error("unable to start embedded postgres", "error", err.Error())
		os.Exit(1)
	}
	defer func() {
		if err := postgres.Stop(); err != nil {
			slog.Error("unable to stop embedded postgres", "error", err.Error())
			os.Exit(1)
		}
	}()

	test(ctx)

}

func test(ctx context.Context) {

	connectionUrl := "postgres://postgres:postgres@127.0.0.1:5555/postgres"

	pgxConfig, err := pgxpool.ParseConfig(connectionUrl)
	if err != nil {
		slog.Error("cannot parse postgres config", "error", err.Error())
		return
	}

	pool, err := pgxpool.NewWithConfig(ctx, pgxConfig)
	if err != nil {
		slog.Error("unable to create pgx connection pool", "error", err.Error())
		return
	}

	if _, err := pool.Exec(ctx, `CREATE TABLE "public"."pgx_test" ("id" text NOT NULL PRIMARY KEY, "value" JSONB);`); err != nil {
		slog.Error("unable to create table 'pgx_test'", "error", err.Error())
		return
	}

	first := &TestData{
		Id: "first",
		Value: &TestValue{
			Data: "test",
		},
	}

	if _, err := pool.Exec(ctx, "", first); err != nil {
		slog.Error("unable to insert first value into table 'pgx_test'", "error", err.Error())
		return
	}

	second := &TestData{
		Id:    "second",
		Value: nil,
	}

	if _, err := pool.Exec(ctx, "", second); err != nil {
		slog.Error("unable to insert second value into table 'pgx_test'", "error", err.Error())
		return
	}

	rows, err := pool.Query(ctx, "SELECT id, value from pgx_test")
	if err != nil {
		slog.Error("unable to query rows from table 'pgx_test'", "error", err.Error())
		return
	}

	testData, err := pgx.CollectRows(rows, pgx.RowToAddrOfStructByName[TestData])
	if err != nil {
		slog.Error("unable to collect rows from table 'pgx_test'", "error", err.Error())
		return
	}

	if testData[0].Value == nil || testData[0].Value.Data != "test" {
		slog.Error("expected testData[0].Value.Data to be 'test'")
		return
	}
	slog.Info("testData[0].Value.Data was 'test'")

	if testData[1].Value != nil {
		slog.Error("expected testData[1].Value to be nil struct")
		return
	}

	slog.Info("testData[1].Value was nil struct")
}
```

*  Previous behaviour - `go mod tidy && go get github.com/jackc/pgx/v5@v5.7.1 && go run main.go`
* New behaviour - `go mod tidy && go get github.com/jackc/pgx/v5@v5.7.2 && go run main.go`

**Expected behavior**
I expected the behaviour to continue between versions, and that the `NULL` column would map to a `nil` struct value.

**Actual behavior**
 The `NULL` column no longer produces a `nil` struct value.

**Version**
 - Go: `$ go version` -> go version go1.23.1 darwin/arm64

**Additional context**

### PR DESCRIPTION
**Pull request by felix-roehrich**
The fix from #2151 just pushed the original problem from #1470 and #1691 further along. This should be a comprehensive solution; also resolves #2229.

### CODE REVIEW

**Comment by felix-roehrich** [comment]
I will add a test to prevent regression from #2229 tomorrow.

**Comment by felix-roehrich** [comment]
@jackc Looking at the following examples, I believe that the current scanning behavior is in inconsistent.

```go
type Foo struct{}

var dst *Foo
err = conn.QueryRow(context.Background(), `select 'null'::jsonb`).Scan(&dst)
// err == nil
// dst == nil

var dst *Foo
err = conn.QueryRow(context.Background(), `select null::jsonb`).Scan(&dst)
// err == nil
// dst == nil

var dst Foo
err = conn.QueryRow(context.Background(), `select 'null'::jsonb`).Scan(&dst)
// err == nil
// dst == Foo{}

var dst Foo
err = conn.QueryRow(context.Background(), `select null::jsonb`).Scan(&dst)
// err == can't scan into dest[0] (col: jsonb): cannot scan NULL into *pgx_test.Foo
// dst == Foo{}
```

I believe either both cases of scanning `Foo` should error or none (or change scanning of `*Foo`). What is your opinion?

**Comment by felix-roehrich** [comment]
I decided to revert #2151 partially. This is because this should never be necessary, as such cases would be handled by the `PointerPointerScanPlan`. JSON requires special care to handle the scanning of `'null'::jsonb`.

**Comment by jackc** [comment]
Thanks! `sql.Scanner` especially plus json has been such a pain. Hopefully, this finally resolves it.

**Comment by emreisikligil** [comment]
Can we add this to the next patch version v5.7.3 please as v5.7.2 has the regression when scanning null jsonb columns into a pointer?

**Comment by jackc** [comment]
@emreisikligil Just released v5.7.3.

**Comment by emreisikligil** [comment]
@jackc Thanks a lot 🙏

**Comment by alicebob** [comment]
Just as a FYI, this did make the behavior of scanning a raw message with the content `null`. If I pass in a jSON value `null`, then I don't get back what I put into it, but a NULL/nil. I don't know the whole history of this change, and I'm sure it's needed somehow, so I put this comment here as a warning/gotcha, maybe it helps someone:

```
    ["CREATE TABLE pgx (jsoncol JSONB NOT NULL DEFAULT 'null')"]
    ["INSERT INTO pgx (jsoncol) VALUES ('null')"]
    var j json.RawMessage
    require.NoError(t, db.QueryRow(ctx, `SELECT jsoncol FROM pgx`).Scan(&j))
    require.Equal(t, json.RawMessage([]byte("null")), j)
```

this now fails in 5.7.3 with:
```
        	Error:      	Not equal: 
        	            	expected: json.RawMessage{0x6e, 0x75, 0x6c, 0x6c}
        	            	actual  : json.RawMessage(nil)
```

The test passes on 5.7.2.

File: pgtype/json.go [hunk 1]
```diff
@@ -202,7 +197,7 @@ type scanPlanJSONToJSONUnmarshal struct {
 }
 
 func (s *scanPlanJSONToJSONUnmarshal) Scan(src []byte, dst any) error {
-	if src == nil {
+	if src == nil || string(src) == "null" {
```
Comment (felix-roehrich) [inline pgtype/json.go:200]: This is due to this change. Which was made with https://github.com/jackc/pgx/pull/2236#issuecomment-2604154556 in mind, however looking at the godoc for the json package, not erroring is intentional. Though I personally don't agree with the rational, it's probably for the best to revert this change.

> // The JSON null value unmarshals into an interface, map, pointer, or slice
// by setting that Go value to nil. Because null is often used in JSON to mean
// “not present,” unmarshaling a JSON null into any other Go type has no effect
// on the value and produces no error.

Comment (jackc) [reply pgtype/json.go:200]: I agree. I think this should be reverted.

Comment (alicebob) [reply pgtype/json.go:200]: Thanks both for the quick reply, and many more thanks for a great library.
